name: weather_forecast_app_zarinpal
description: My flutter project for ZarinPal's interview :D
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  bloc: ^8.1.2
  equatable: ^2.0.5
  dio: ^5.4.0
  dartz: ^0.10.1
  country_flags: ^2.2.0
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.3.1
  flex_color_scheme: ^7.2.0
  flutter_spinkit: ^5.1.0
  # google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/app_icon.png"

flutter:
  uses-material-design: true


  fonts:
      - family: cm
        fonts:
          - asset: lib/assets/fonts/ChelseaMarket-Regular.ttf
      - family: roboto
        fonts:
          - asset: lib/assets/fonts/Roboto-Light.ttf
      - family: thegirl
        fonts:
          - asset: lib/assets/fonts/TheGirlNextDoor-Regular.ttf